#!/bin/bash
# 90-finish: verify everything, save credentials, print summary.
set -euo pipefail
source "$(dirname "$0")/common.sh"

if [ "$HAVE_SSL" = "1" ]; then
  PANEL_URL="https://$DOMAIN:$HTTPS_PORT"
else
  PANEL_URL="http://$DOMAIN:$HTTP_PORT"
fi

log "Verifying services..."
for s in nginx php8.5-fpm redis-server mariadb docker wings; do
  systemctl is-active "$s" >/dev/null || die "$s is not running."
done

log "Verifying panel responds..."
CODE="$(curl -sk -o /dev/null -w "%{http_code}" --max-time 30 "$PANEL_URL/")"
[ "$CODE" = "200" ] || die "Panel at $PANEL_URL returned HTTP $CODE."

log "Verifying wings ports..."
port_in_use "$WINGS_PORT" || die "Nothing listening on wings port $WINGS_PORT."
port_in_use "$SFTP_PORT" || warn "Nothing on SFTP port $SFTP_PORT yet (normal until first server runs)."

CREDS=/root/panel-credentials.env
cat > "$CREDS" <<CREDS
# Generated by panel-installer on $(date -u +%F). Keep root-only (chmod 600).
PANEL_URL=$PANEL_URL
ADMIN_USER=$ADMIN_USER
ADMIN_PASS=$ADMIN_PASS
ADMIN_EMAIL=$EMAIL
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASS=$DB_PASS
DOMAIN=$DOMAIN
HTTP_PORT=$HTTP_PORT
HTTPS_PORT=$HTTPS_PORT
WINGS_PORT=$WINGS_PORT
SFTP_PORT=$SFTP_PORT
NODE_NAME=$NODE_NAME
HAVE_SSL=$HAVE_SSL
CREDS
chmod 600 "$CREDS"

cat <<SUMMARY | tee -a "$LOG"

================================================================
  INSTALL COMPLETE
  Panel:      $PANEL_URL
  Login:      $ADMIN_USER  (password saved in $CREDS)
  Modpacks:   $PANEL_URL/browse  + in-form popup on Create Server
  Wings:      port $WINGS_PORT, SFTP $SFTP_PORT
  Node:       $NODE_NAME ($NODE_MEM MB RAM, $NODE_DISK MB disk)
  Game ports: $PUBIP $PORT_START-$((PORT_START + PORT_COUNT - 1))
  SSL:        $([ "$HAVE_SSL" = "1" ] && echo "Let's Encrypt active" || echo "NOT configured - see warnings above")
  Rule of thumb: run only ONE big modpack (RLCraft etc.) at a time
  unless the box has 6 GB+ RAM free per server.
================================================================
SUMMARY
log "Credentials saved to $CREDS (chmod 600)."
